### ISSUE TITLE
How to build/deploy monorepo with several APIs where each API has smoke test and DB migration projects

### ISSUE THREAD

**Issue by cmeeren** [leonardochaia/dotnet-affected#69]
Not sure this is the best place to ask, but it is at least somewhat related to dotnet-affected, and given the helpful responses I have received so far here, I figured I'd try.

I have a monorepo with many APIs. Each API has a smoke test project and a DB migrations project. These do not have a project reference to the API project (I could add that if needed as a workaround), but they should still always be built and packaged (as separate artifacts) along with the API, so that when the API is deployed, the release pipeline can run the DB migrations and smoke tests.

Our migration to a monorepo has just been completed and there is still work left to do. Currently I am not using dotnet-affected. Each API still has a separate Azure DevOps pipeline for build (YAML) and deploy (UI). I have set up path triggers in the build pipelines so that the APIs are rebuilt for changes to files I know may influence the build. This gives many false positives, it's fairly high maintenance in the face of refactors (since project references are not picked up and have to be manually added to the path trigger list), and of course means that common libraries are restored/re-built many times (once for each pipeline).

I would like to experiment with dotnet-affected, but I'm not sure how best to accomplish what I need, which is this:

- Build everything that has changed for each push (changed since the last _successful_ build)
- If an API is built, also build its smoke tests and DB migrations projects (the best way to do this might be to just add a project reference to the main API project, even though it's a hack)
- Pack and publish the API project, DB migrations project and smoke test project as artifacts to a release pipeline (a separate pipeline for each API), and only do this for the built/changed APIs (including if there are changes only to the smoke test project or DB migrations project)

How can this best be accomplished using dotnet-affected?

**Comment by leonardochaia** [comment]
Hi @cmeeren , 
I can think of some ideas for your setup.

So, dotnet-affected works by analyzing your dotnet projects. If the migrations (or smoke test but i'll just say migrations for short) project don't have a `ProjectReference` to the api project, they will not be considered affected when API changes.
Easiest way to let dotnet-affected know of these projects is to add the `ProjectReference` to the migrations project, you could do it with a condition so that it is only referenced on CI.

> Build everything that has changed for each push (changed since the last successful build)

To build what has changed whenever a push happens, your pipeline needs to:
1. determine last successful commit for this branch (take a look at [nx docs for Azure pipelines](https://nx.dev/recipes/other/azure-last-successful-commit)
2. install dotnet-affected tool: we recommend to use dotnet local tool
3. run dotnet-affected from source commit to target commit
4. run dotnet build against the traversal project output by dotnet-affected

Here's an untested azure pipelines example, unfortunately I don't have any public real-use example to share for Azure Pipelines (we do have it for Github Actions)

```yml
pr:
  - main

variables:
  CI: 'true'
  DEFAULT_COMMIT_SOURCE: $(git rev-parse HEAD~1)
  TARGET_COMMIT: $(git rev-parse $SYSTEM_PULLREQUEST_TARGETBRANCH)
jobs:
  - job: main
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # Credits to https://nx.dev/recipes/other/azure-last-successful-commit
      # Set Azure Devops CLI default settings
      - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
        displayName: 'Set default Azure DevOps organization and project'

      # Get last successfull commit from Azure Devops CLI
      - bash: |
          LAST_SHA=$(az pipelines build list --branch $(Build.SourceBranchName) --definition-ids $(System.DefinitionId) --result succeeded --top 1 --query "[0].triggerInfo.\"ci.sourceSha\"")
          if [ -z "$LAST_SHA" ]
          then
            LAST_SHA=$DEFAULT_COMMIT_SOURCE
          fi
          echo "Last successful commit SHA: $LAST_SHA"
          echo "##vso[task.setvariable variable=COMMIT_SOURCE]$LAST_SHA"
        displayName: 'Get last successful commit SHA'
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      - task: UseDotNet@2
        displayName: 'Installing DotNet SDK'
        inputs:
          version: 7.x

        # Restore Tools
      - script: dotnet tool restore --tool-manifest .config/dotnet-tools.json
        displayName: Restoring Tools

        # Run dotnet affected
      - script: |
          dotnet affected --verbose \
            -p $(System.DefaultWorkingDirectory) \
            --from $(COMMIT_SOURCE) \
            --to $(TARGET_COMMIT) \
            --format traversal text

          exitCode="$?"
          if [ "$exitCode" -eq 0 ]; then
            # changes happen, we'll need to build them
            cat affected.proj
            echo "##vso[task.setvariable variable=HAS_CHANGES]true"
          elif [ "$exitCode" -eq 166 ]; then
            # nothing changed. No need to build
            echo `##vso[task.complete result=Succeeded;]DONE`
            exit 0
          else
            exit $exitCode
          fi
        displayName: Run dotnet-affected

        # Restore
      - script: dotnet restore affected.proj
        displayName: Run dotnet restore
        condition: and(succeeded(), eq(variables.HAS_CHANGES, 'true'))

        # Build
      - script: |
          dotnet build affected.proj \
            --no-incremental \
            /dl:"CentralLogger,$(logger_assembly_path)*ForwardingLogger,$(logger_assembly_path)" \
            /clp:NoSummary \
            /nologo \
            /WarnAsError
        displayName: Run dotnet build
        condition: and(succeeded(), eq(variables.HAS_CHANGES, 'true'))
```

Regarding your last point:

> Pack and publish the API project, DB migrations project and smoke test project as artifacts to a release pipeline (a separate pipeline for each API), and only do this for the built/changed APIs (including if there are changes only to the smoke test project or DB migrations project)

You can use the `affected.txt` file that will get generated to known which projects have changed+affected and need to get re-deployed. This can be uploaded as a build artifact as well.

We have plans to for a JSON formatter as well #35 

Finally, I would like to mention that you might wanna give a look at `DotnetAffected.Tasks`, which is an MSBuild task that can be used to run dotnet affected directly without the CLI. If you are handy with MSBuild, this should allow you to perform a bunch of customizations to the build.

`DotnetAffected.Tasks` is quite new and I am not yet using it for any project, however, there's [documentation here](https://github.com/leonardochaia/dotnet-affected/blob/main/src/DotnetAffected.Tasks/README.md) and [several examples](https://github.com/leonardochaia/dotnet-affected/tree/main/src/DotnetAffected.Tasks/Examples) and [tests](https://github.com/leonardochaia/dotnet-affected/tree/main/test/DotnetAffected.Tasks.Tests) as well.

I hope I haven't missed any of your questions, feel free to ask, I'll be happy to answer as soon as I find the time.
BTW, it would be great to have some docs on this repo about configuring Azure Pipelines CI. If you happen to have the time to write down all this information plus your findings into a markdown file, I'll be happy to merge a PR.

Thanks for the feedback and for trying out the tool.

Kind regards,
Leo.
